services:
  podping:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      HIVE_ACCOUNT_NAME: ${HIVE_ACCOUNT_NAME}
      HIVE_POSTING_KEY: ${HIVE_POSTING_KEY}
      PODPING_SHARED_SECRET: ${PODPING_SHARED_SECRET}
    restart: unless-stopped
